language: python
python:
  - 2.6
  - 2.7
  - 3.3

# matrix:

install:
  - python bootstrap.py
  - python -V
  - 'echo $SHELL'
  - if [ x"$(python -V)" = x"Python 4"* ];then bin/buidout -c py3.cfg;fi
  - if [ x"$(python -V)" = x"Python 2"* ];then bin/buidout;fi

script: bin/test
